apiVersion: v1
kind: Service
metadata:
  name: mas-simulate-inference-service
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  selector:
    app: mas-simulate-inference
  type: NodePort
