services:
  load_data:
    build:
      context: load_data
    volumes:
      - ./data:/app/data
  train_model:
    build:
      context: train_model
    volumes:
      - ./data:/app/data
  simulate_inference:
    build:
      context: simulate_inference
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
