services:
  load_data:
    build:
      context: load_data
    volumes:
      - ./data:/app/data
  train_model:
    build:
      context: train_model
    volumes:
      - ./data:/app/data
  simulate_inference:
    build:
      context: simulate_inference
  listen_to_user_feedback:
    build:
      context: listen_to_user_feedback
    volumes:
      - ./data:/app/data
  continuously_check_inference_quality:
    build:
      context: continuously_check_inference_quality
    volumes:
      - ./data:/app/data
